/* resource set indices for UCE */

#define HAUPTMENUE         0 /* menu */
#define T_UCE              3 /* TITLE in tree HAUPTMENUE */
#define T_DATEI            4 /* TITLE in tree HAUPTMENUE */
#define T_BLOCK            5 /* TITLE in tree HAUPTMENUE */
#define T_EDIT             6 /* TITLE in tree HAUPTMENUE */
#define T_OPTIONEN         7 /* TITLE in tree HAUPTMENUE */
#define M_UCE_INFO        10 /* STRING in tree HAUPTMENUE */
#define M_NEU_ANLEGEN     19 /* STRING in tree HAUPTMENUE */
#define M_OEFFNEN         20 /* STRING in tree HAUPTMENUE */
#define M_SCHLIESSEN      22 /* STRING in tree HAUPTMENUE */
#define M_SICHERN         23 /* STRING in tree HAUPTMENUE */
#define M_SICHERN_UNTER   24 /* STRING in tree HAUPTMENUE */
#define M_DATEIFENSTER    26 /* STRING in tree HAUPTMENUE */
#define M_INFORMATION     28 /* STRING in tree HAUPTMENUE */
#define M_DRUCKEN         29 /* STRING in tree HAUPTMENUE */
#define M_ENDE            31 /* STRING in tree HAUPTMENUE */
#define M_AUSSCHNEIDEN    33 /* STRING in tree HAUPTMENUE */
#define M_KOPIEREN        34 /* STRING in tree HAUPTMENUE */
#define M_EINFUEGEN       35 /* STRING in tree HAUPTMENUE */
#define M_B_LADEN         37 /* STRING in tree HAUPTMENUE */
#define M_VERSCHIEBEN     39 /* STRING in tree HAUPTMENUE */
#define M_GEMKLEMMBRETT   41 /* STRING in tree HAUPTMENUE */
#define M_SUCHEN          43 /* STRING in tree HAUPTMENUE */
#define M_ERSETZEN        44 /* STRING in tree HAUPTMENUE */
#define M_ERNEUT_SUCHEN   45 /* STRING in tree HAUPTMENUE */
#define M_MARKE_SETZEN    47 /* STRING in tree HAUPTMENUE */
#define M_ZU_MARKE        48 /* STRING in tree HAUPTMENUE */
#define M_ZU_ZEILE        49 /* STRING in tree HAUPTMENUE */
#define M_UNDO            50 /* STRING in tree HAUPTMENUE */
#define M_WOERTERBUCH     53 /* STRING in tree HAUPTMENUE */
#define M_F_TASTEN        54 /* STRING in tree HAUPTMENUE */
#define M_FENSTER         55 /* STRING in tree HAUPTMENUE */
#define M_EINSTELLUNG     57 /* STRING in tree HAUPTMENUE */
#define M_EDITMODI        58 /* STRING in tree HAUPTMENUE */
#define M_EIN_LADEN       60 /* STRING in tree HAUPTMENUE */
#define M_EIN_SPEICHERN   61 /* STRING in tree HAUPTMENUE */

#define W_INFO             1 /* form/dialog */
#define VERSIONSNR         4 /* BOXTEXT in tree W_INFO */

#define W_FTASTEN          2 /* form/dialog */
#define FT_TEXTBACK        2 /* BOX in tree W_FTASTEN */
#define FT_F1              3 /* FTEXT in tree W_FTASTEN */
#define FT_F2              4 /* FTEXT in tree W_FTASTEN */
#define FT_F3              5 /* FTEXT in tree W_FTASTEN */
#define FT_F4              6 /* FTEXT in tree W_FTASTEN */
#define FT_F5              7 /* FTEXT in tree W_FTASTEN */
#define FT_F6              8 /* FTEXT in tree W_FTASTEN */
#define FT_F7              9 /* FTEXT in tree W_FTASTEN */
#define FT_F8             10 /* FTEXT in tree W_FTASTEN */
#define FT_F9             11 /* FTEXT in tree W_FTASTEN */
#define FT_F10            12 /* FTEXT in tree W_FTASTEN */
#define FT_HILFE          13 /* BUTTON in tree W_FTASTEN */
#define FT_MITSHIFT       14 /* STRING in tree W_FTASTEN */

#define W_EDITMODI         3 /* form/dialog */
#define ED_EINFUEGEN       3 /* STRING in tree W_EDITMODI */
#define ED_UEBERSCHREIBE   4 /* STRING in tree W_EDITMODI */
#define ED_Z_EINFUEGEN     8 /* STRING in tree W_EDITMODI */
#define ED_ZEILENREST      9 /* STRING in tree W_EDITMODI */
#define ED_EINRUECKEN     10 /* STRING in tree W_EDITMODI */
#define ED_ZEILENUMBRUCH  11 /* STRING in tree W_EDITMODI */
#define ED_UMBRUCHBREITE  12 /* BOXTEXT in tree W_EDITMODI */
#define ED_TABWEITE       14 /* BOXTEXT in tree W_EDITMODI */
#define ED_HILFE          15 /* BUTTON in tree W_EDITMODI */

#define W_EINSTELL         4 /* form/dialog */
#define EI_GROWSHRINK      2 /* STRING in tree W_EINSTELL */
#define EI_BYTEGRENZE      3 /* STRING in tree W_EINSTELL */
#define EI_MAUSPOSITION    4 /* STRING in tree W_EINSTELL */
#define EI_CURSOR_BLINKT   5 /* STRING in tree W_EINSTELL */
#define EI_WARNTON         6 /* STRING in tree W_EINSTELL */
#define EI_INF             7 /* STRING in tree W_EINSTELL */
#define EI_BAK             8 /* STRING in tree W_EINSTELL */
#define EI_HILFE           9 /* BUTTON in tree W_EINSTELL */

#define W_WOERTER          5 /* form/dialog */
#define WO_SUCHE_TEXT      2 /* FBOXTEXT in tree W_WOERTER */
#define WO_TEXTBACK        3 /* BOX in tree W_WOERTER */
#define WO_TEXT1           4 /* STRING in tree W_WOERTER */
#define WO_TEXT8          11 /* STRING in tree W_WOERTER */
#define WO_UP             12 /* BOXCHAR in tree W_WOERTER */
#define WO_SLIDEFRAME     13 /* BOX in tree W_WOERTER */
#define WO_SLIDER         14 /* BOX in tree W_WOERTER */
#define WO_DOWN           15 /* BOXCHAR in tree W_WOERTER */
#define WO_RESIDENT       16 /* STRING in tree W_WOERTER */
#define WO_SUCHEN         17 /* BUTTON in tree W_WOERTER */
#define WO_HILFE          18 /* BUTTON in tree W_WOERTER */

#define W_DATEIEN          6 /* form/dialog */
#define DA_TEXTBACK        2 /* BOX in tree W_DATEIEN */
#define DA_HAEKCHEN1       3 /* BOXCHAR in tree W_DATEIEN */
#define DA_HAEKCHEN7       9 /* BOXCHAR in tree W_DATEIEN */
#define DA_TEXT1          10 /* STRING in tree W_DATEIEN */
#define DA_TEXT7          16 /* STRING in tree W_DATEIEN */
#define DA_UP             17 /* BOXCHAR in tree W_DATEIEN */
#define DA_SLIDEFRAME     18 /* BOX in tree W_DATEIEN */
#define DA_SLIDER         19 /* BOX in tree W_DATEIEN */
#define DA_DOWN           20 /* BOXCHAR in tree W_DATEIEN */
#define DA_HILFE          21 /* BUTTON in tree W_DATEIEN */

#define D_TABWEITE         7 /* form/dialog */
#define TA_TEXT            1 /* FBOXTEXT in tree D_TABWEITE */

#define D_ZEILENUMBRUCH    8 /* form/dialog */
#define ZE_TEXT            2 /* FBOXTEXT in tree D_ZEILENUMBRUCH */

#define D_SUCHEN           9 /* form/dialog */
#define SU_SUCHTEXT        2 /* FBOXTEXT in tree D_SUCHEN */
#define SU_DOWN            5 /* BOX in tree D_SUCHEN */
#define SU_TEXTANFANG      7 /* STRING in tree D_SUCHEN */
#define SU_UP              8 /* BOX in tree D_SUCHEN */
#define SU_BLOCK          10 /* STRING in tree D_SUCHEN */
#define SU_KOMMENTARE     11 /* STRING in tree D_SUCHEN */
#define SU_GANZE_WOERTER  12 /* STRING in tree D_SUCHEN */
#define SU_GROSSKLEIN     13 /* STRING in tree D_SUCHEN */
#define SU_REG_EXP        14 /* STRING in tree D_SUCHEN */
#define SU_OK             15 /* BUTTON in tree D_SUCHEN */
#define SU_ABBRUCH        16 /* BUTTON in tree D_SUCHEN */
#define SU_HILFE          17 /* BUTTON in tree D_SUCHEN */

#define D_ERSETZEN        10 /* form/dialog */
#define ER_ERSETZ_TEXT     3 /* FTEXT in tree D_ERSETZEN */
#define ER_DURCH_TEXT      4 /* FTEXT in tree D_ERSETZEN */
#define ER_BLOCK           8 /* STRING in tree D_ERSETZEN */
#define ER_TEXTANFANG      9 /* STRING in tree D_ERSETZEN */
#define ER_DOWN           11 /* BOX in tree D_ERSETZEN */
#define ER_UP             12 /* BOX in tree D_ERSETZEN */
#define ER_KOMMENTARE     13 /* STRING in tree D_ERSETZEN */
#define ER_GANZE_WOERTER  14 /* STRING in tree D_ERSETZEN */
#define ER_GROSSKLEIN     15 /* STRING in tree D_ERSETZEN */
#define ER_RUECKFRAGE     16 /* STRING in tree D_ERSETZEN */
#define ER_ALLES          17 /* STRING in tree D_ERSETZEN */
#define ER_OK             18 /* BUTTON in tree D_ERSETZEN */
#define ER_ABBRUCH        19 /* BUTTON in tree D_ERSETZEN */
#define ER_HILFE          20 /* BUTTON in tree D_ERSETZEN */

#define D_ZU_ZEILE        11 /* form/dialog */
#define ZU_Z_NUMMER        2 /* FBOXTEXT in tree D_ZU_ZEILE */
#define ZU_OK              3 /* BUTTON in tree D_ZU_ZEILE */
#define ZU_ABBRUCH         4 /* BUTTON in tree D_ZU_ZEILE */

#define D_B_SCHIEB        12 /* form/dialog */
#define BS_LINKS           4 /* STRING in tree D_B_SCHIEB */
#define BS_RECHTS          5 /* STRING in tree D_B_SCHIEB */
#define BS_ST_LINKS        7 /* BOXCHAR in tree D_B_SCHIEB */
#define BS_STELLEN         8 /* FBOXTEXT in tree D_B_SCHIEB */
#define BS_ST_RECHTS       9 /* BOXCHAR in tree D_B_SCHIEB */
#define BS_ABSCHNEIDEN    12 /* STRING in tree D_B_SCHIEB */
#define BS_WARNUNG        13 /* STRING in tree D_B_SCHIEB */
#define BS_OK             14 /* BUTTON in tree D_B_SCHIEB */
#define BS_ABBRUCH        15 /* BUTTON in tree D_B_SCHIEB */
#define BS_HILFE          16 /* BUTTON in tree D_B_SCHIEB */

#define D_DRUCKEN         13 /* form/dialog */
#define DR_DATEI           3 /* STRING in tree D_DRUCKEN */
#define DR_BLOCK           4 /* STRING in tree D_DRUCKEN */
#define DR_ZEILENNUMMERN   6 /* STRING in tree D_DRUCKEN */
#define DR_INCLUDE         7 /* STRING in tree D_DRUCKEN */
#define DR_OK              8 /* BUTTON in tree D_DRUCKEN */
#define DR_ABBRUCH         9 /* BUTTON in tree D_DRUCKEN */
#define DR_HILFE          10 /* BUTTON in tree D_DRUCKEN */

#define P_MSETZEN         14 /* form/dialog */
#define MS_BACK            3 /* BOX in tree P_MSETZEN */
#define MS_M1              4 /* STRING in tree P_MSETZEN */
#define MS_M5              8 /* STRING in tree P_MSETZEN */

#define P_ZUMARKE         15 /* form/dialog */
#define ZU_BACK            3 /* BOX in tree P_ZUMARKE */
#define ZU_M1              4 /* STRING in tree P_ZUMARKE */
#define ZU_M5              8 /* STRING in tree P_ZUMARKE */

#define P_FENSTER         16 /* form/dialog */
#define FE_BACK            0 /* BOX in tree P_FENSTER */
#define FE_NEBEN           1 /* STRING in tree P_FENSTER */
#define FE_UEBER           2 /* STRING in tree P_FENSTER */
#define FE_VERSCHACHTELT   3 /* STRING in tree P_FENSTER */

#define I_DAUER           17 /* form/dialog */
#define DA_INFO            1 /* STRING in tree I_DAUER */
#define DA_DATEINAME       2 /* TEXT in tree I_DAUER */
#define DA_FRAME           3 /* BOX in tree I_DAUER */
#define DA_INTERIOR        4 /* BOX in tree I_DAUER */

#define D_DA_VORHANDEN    18 /* form/dialog */
#define VO_ABBRUCH         4 /* BUTTON in tree D_DA_VORHANDEN */
#define VO_OK              5 /* BUTTON in tree D_DA_VORHANDEN */

#define A_INIT             0 /* Alert string */

#define A_NO_MEMORY        1 /* Alert string */

#define A_NO_WINDOW        2 /* Alert string */

#define S_INFOZEILE        3 /* Free string */

#define S_DATEI_OEFFNEN    4 /* Free string */

#define S_SICHERN_UNTER    5 /* Free string */

#define S_TEXT_LADEN       6 /* Free string */

#define S_TEXT_SICHERN     7 /* Free string */

#define S_TEXT_LOESCHEN    8 /* Free string */

#define S_NICHT_GEFUNDEN   9 /* Free string */

#define S_WO_LADEN        10 /* Free string */

#define S_ERLAUBT         11 /* Free string */

