/* resource set indices for WOERTER */

#define M_MENUE            0 /* menu */
#define T_WOERTERBUCH      3 /* TITLE in tree M_MENUE */
#define T_OPTIONEN         4 /* TITLE in tree M_MENUE */
#define M_INFO             7 /* STRING in tree M_MENUE */
#define M_WOERTERBUCH     16 /* STRING in tree M_MENUE */
#define M_NEUES_WORT      17 /* STRING in tree M_MENUE */
#define M_TRAINER         18 /* STRING in tree M_MENUE */
#define M_ENDE            20 /* STRING in tree M_MENUE */

#define W_INFO             1 /* form/dialog */

#define W_WOERTERBUCH      2 /* form/dialog */
#define WO_ORGINAL         3 /* FTEXT in tree W_WOERTERBUCH */
#define WO_FRAME           5 /* BOX in tree W_WOERTERBUCH */
#define WO_WORT1           6 /* STRING in tree W_WOERTERBUCH */
#define WO_WORT8          13 /* STRING in tree W_WOERTERBUCH */
#define WO_UP             14 /* BOXCHAR in tree W_WOERTERBUCH */
#define WO_SLIDEFRAME     15 /* BOX in tree W_WOERTERBUCH */
#define WO_SLIDER         16 /* BOX in tree W_WOERTERBUCH */
#define WO_RAHMEN         19 /* BOX in tree W_WOERTERBUCH */
#define WO_UEBER1         20 /* STRING in tree W_WOERTERBUCH */
#define WO_UEBER5         24 /* STRING in tree W_WOERTERBUCH */
#define WO_DOWN           25 /* BOXCHAR in tree W_WOERTERBUCH */
#define WO_D_E            27 /* STRING in tree W_WOERTERBUCH */
#define WO_E_D            28 /* STRING in tree W_WOERTERBUCH */
#define WO_SUCHE          30 /* BUTTON in tree W_WOERTERBUCH */
#define WO_LOESCHEN       31 /* BUTTON in tree W_WOERTERBUCH */
#define WO_WORTZAHL       33 /* STRING in tree W_WOERTERBUCH */

#define W_NEUES_WORT       3 /* form/dialog */
#define NE_ORGINAL         3 /* FTEXT in tree W_NEUES_WORT */
#define NE_UEBER1          4 /* FTEXT in tree W_NEUES_WORT */
#define NE_UEBER5          8 /* FTEXT in tree W_NEUES_WORT */
#define NE_WORTZAHL       10 /* STRING in tree W_NEUES_WORT */
#define NE_AUFNEHMEN      11 /* BUTTON in tree W_NEUES_WORT */
#define NE_D_E            13 /* STRING in tree W_NEUES_WORT */
#define NE_E_D            14 /* STRING in tree W_NEUES_WORT */

#define W_TRAINER          4 /* form/dialog */
#define TR_RAHMEN          1 /* BOX in tree W_TRAINER */
#define TR_SUCHWORT        2 /* STRING in tree W_TRAINER */
#define TR_RAHMEN2         4 /* BOX in tree W_TRAINER */
#define TR_ANTWORT         5 /* FTEXT in tree W_TRAINER */
#define TR_D_E             8 /* STRING in tree W_TRAINER */
#define TR_E_D             9 /* STRING in tree W_TRAINER */
#define TR_GEMISCHT       10 /* STRING in tree W_TRAINER */
#define TR_PROZENT        13 /* STRING in tree W_TRAINER */
#define TR_OK             15 /* BUTTON in tree W_TRAINER */

#define S_INFO             0 /* Free string */

#define S_WOERTERBUCH      1 /* Free string */

#define S_NEUES_WORT       2 /* Free string */

#define S_TRAINER          3 /* Free string */

#define S_NICHT_GEFUNDEN   4 /* Free string */

